#!/bin/bash

# git fetch
remoteBranch=$(git symbolic-ref --short -q HEAD)

if [ ! -z "$1" ]
then
  remoteBranch=$1
fi
echo "Showing diff between $remoteBranch origin/$remoteBranch"
insertions=$(git diff --stat -U3 HEAD^^^ HEAD)
# deletions=$(git diff --stat -U3 HEAD HEAD^^ | grep -E '^\-')
# echo "Insertions: $insertions\n\n\n"
echo "Awked\n"

embed_chunk() {
  embedding=$(curl -s https://api.openai.com/v1/embeddings \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "{
    \"input\": \"$1\",
    \"model\": \"text-embedding-3-small\"
  }" | jq -r '.data[0].embedding')

}

declare -a chunks
chunk=""
while IFS= read -r line; do
  if [[ $line =~ (@@).+(@@ ) ]]; then
    if [ ! -z "$chunk" ]; then
      chunks+=("$chunk")
    fi
    chunk=""
  else
    chunk="$chunk\n$line"
  fi
done <<< $insertions

# # Print all chunks (optional - you can remove this if you don't need it)
# for chunk in "${chunks[@]}"; do
#   embed_chunk "$chunk"
#   echo "Embedding: $embedding"
# done


embed_chunk "Hello, world!"
# echo $embedding